version: '3.7'

services:
  smart-brain-api:
    container_name: backend
#    image: node:10.18.0
    build: ./
    command: npm start
    working_dir: /var/www/smart-brain-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/smart-brain-api